### ISSUE TITLE
Unknown system error #193

### ISSUE THREAD

**Issue by rkgttr** [caiguanhao/grunt-ziti#3]
Hi,

First the URL for webify doesn't exist anymore apparently, I had to download it manually. Not a big deal.
But then, each time I run the grunt task, I have an error when it comes to run the ziti task:

```
Running "ziti:index" (ziti) task
>> Characters: Helo wrd!ThisML5Bpat.
Fatal error: spawn Unknown system errno 193
```

No ttf file is created, only a *.ttf.chars file.

Thanks.

**Comment by caiguanhao** [comment]
I have updated the webify download URL and fixed a bug in font-optimizer. I have also updated the repository on NPM. You can try the latest version and see if the error still exists. If exists, please tell me your operating system, system architecture, node version, gruntfile config.

**Comment by rkgttr** [comment]
Wow that was fast, thanks. I can't test it today as I'm busy on something else. I'll let you know ASAP if this has solved my issue :)

**Comment by rkgttr** [comment]
Hi,

Webify downloads correctly now, but I still have the an error when I launch the grunt task:

    Fatal error: spawn UNKNOWN

My grunt task looks like this:

    ziti: {
      index: {
        options: {
          html: {
            pattern: '\\.html?$',
            classes: [ '' ],
            attributes: [ '' ],
            elements: [ 'h2', 'p' ],
            comments: [ '' ]
          },
          font: {
            pattern: '\\.ttf$'
          },
          subset: true,
          optimize: true,
          convert: true,
          deleteCharsFile: false
        },
        files: {
          'app/build/fonts/VAG.ttf': [
            'app/src/index.html',
            'app/src/fonts/VAG.ttf'
          ]
        }
      }
    }

I'm on Windows 10 Pro 64 bits, on Node 0.12.7.

Thanks.

**Comment by caiguanhao** [comment]
I have fixed some bugs on Windows, you can try the latest version. font-optimizer may have some problems if you are using perl 5.22. perl 5.20 is OK.

**Comment by rkgttr** [comment]
All fixed, thanks!
